# API User
@host = http://localhost:3000/api/user
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNTQxMTgzMjA3fQ.6pMeVJw1O22E_p3QCamz_w7IN4RqKERnBk9y1JautLw
GET {{host}}
###
POST {{host}}
content-type: application/json

{
  "username": "Bob",
  "password": "qwerty"
}
###
GET {{host}}/1
###
PATCH {{host}}/1
content-type: application/json

{
  "username": "Bob"
}
###
DELETE {{host}}/1
###
GET http://localhost:3000/api/me
Authorization: Bearer {{token}}
###
POST http://localhost:3000/api/login
content-type: application/json

{
  "username": "Bob1",
  "password": "qwerty"
}
